[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
env_logger = "0.9.0"

async-trait = "0.1.52"
byteorder = "1.4.3"
chrono = "0.4.19"
mysql_common = { version = "0.29.0", features = ["chrono"] }
nom = "7.1.0"
tokio = { version = "1.17.0", features = ["full"] }
opensrv-mysql = {path="../opensrv-mysql"}
mysql_async = "0.30.0"

clap = {version="3.2.14",features = [ "derive" ]}

slab = "0.4.7"
sqlparser = "0.18.0"
redis = "0.21.5"
serde = {version="1.0.140",features = ["derive"],default-features = false}
serde_json = "1.0"
