//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "metric_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub sql_str: String,
    pub db_server_ip: String,
    pub db_server_port: String,
    pub database_name: String,
    pub duration: i32,
    pub max_duration: i32,
    pub exec_count: i32,
    pub cache_hit_count: i32,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
