on: [ push ]

name: Build

jobs:
  build:
    name: x86_64-pc-windows-msvc
    runs-on: windows-2022
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
        version:
          - nightly
    steps:
      - uses: actions/checkout@v2
      # install OpenSSL on Windows
      # TODO: GitHub actions docs state that OpenSSL is
      # already installed on these Windows machines somewhere
      - name: Set vcpkg root
        if: matrix.target == 'x86_64-pc-windows-msvc'
        run: echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Install OpenSSL
        if: matrix.target == 'x86_64-pc-windows-msvc'
        run: vcpkg install openssl:x64-windows

      - name: Install ${{ matrix.version }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{matrix.version}}
          target: ${{ matrix.target }}
          override: true
      - name: workaround MSRV issues
        if: matrix.version != 'stable'
        run: |
          cargo update -p=zstd-sys --precise=2.0.1+zstd.1.5.2
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v1.2.0

      - name: build
        if: ${{ matrix.target != 'x86_64-unknown-linux-musl'}}
        run: |
          cargo +nightly build --target=${{ matrix.target }} --release
      - name: Build Linux Musl
        uses: jean-dfinity/rust-musl-action@master
        if: ${{ matrix.target == 'x86_64-unknown-linux-musl'}}
        with:
          args: rustup default nightly && rustup target add x86_64-unknown-linux-musl && cargo +nightly build --target=${{ matrix.target }} --release

      - name: Zip the Build
        run: |
          pwd
          ls -al target
          ls -al target/${{matrix.target}}
          file target/${{matrix.target}}/release/admin
          file target/${{matrix.target}}/release/server
          
          cd target/${{matrix.target}}/release
          ls -al
          sudo zip -r ${{ matrix.target }}.zip admin* server* -x admin.d -x admin.pdb -x server.d -x server.pdb

      - name: Get current Commit ID
        id: branch
        run: echo "::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ steps.branch.outputs.branch }}
          release_name: ${{ steps.branch.outputs.branch }}
          body: TODO New Release.
          draft: false
          prerelease: false
          allowUpdates: true

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/${{matrix.target}}/release/${{ matrix.target }}.zip
          asset_name: ${{ matrix.target }}.zip
          asset_content_type: application/zip

      - name: Clear the cargo caches
        run: |
          cargo install cargo-cache --version 0.8.2 --no-default-features --features ci-autoclean
          cargo-cache
