on: [ push ]

name: Build

jobs:
  build:
    name: ${{ matrix.target.name }} / ${{ matrix.version }}
    runs-on: ${{ matrix.target.os }}
    strategy:
      matrix:
        target:
#          - { name: Linux, os: ubuntu-latest, triple: x86_64-unknown-linux-gnu }
#          - { name: macOS, os: macos-latest, triple: x86_64-apple-darwin }
          - { name: Windows, os: windows-2022, triple: x86_64-pc-windows-msvc }
        version:
          - nightly
    steps:
      - uses: actions/checkout@v2
      # install OpenSSL on Windows
      # TODO: GitHub actions docs state that OpenSSL is
      # already installed on these Windows machines somewhere
      - name: Set vcpkg root
        if: matrix.target.triple == 'x86_64-pc-windows-msvc'
        run: echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Install OpenSSL
        if: matrix.target.triple == 'x86_64-pc-windows-msvc'
        run: vcpkg install openssl:x64-windows

      - name: Install ${{ matrix.version }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{matrix.version}}
          target: ${{ matrix.target.triple }}
          override: true
      - name: workaround MSRV issues
        if: matrix.version != 'stable'
        run: |
          cargo update -p=zstd-sys --precise=2.0.1+zstd.1.5.2
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v1.2.0

      - name: build
        if: ${{ matrix.target.triple != 'x86_64-unknown-linux-musl'}}
        run: |
          cargo +nightly build --target=${{ matrix.target.triple }} --release
      - name: Build Linux Musl
        uses: jean-dfinity/rust-musl-action@master
        if: ${{ matrix.target.triple == 'x86_64-unknown-linux-musl'}}
        with:
          args: rustup default nightly && rustup target add x86_64-unknown-linux-musl && cargo +nightly build --target=${{ matrix.target.triple }} --release

      - name: Zip the Build
        run: |
          pwd
          ls -al target
          ls -al target/${{matrix.target.triple}}
          file target/${{matrix.target.triple}}/release/admin
          file target/${{matrix.target.triple}}/release/server
          
          cd target/${{matrix.target.triple}}/release
          ls -al
          sudo zip -r ${{ matrix.target.triple }}.zip admin* server* -x admin.d -x admin.pdb -x server.d -x server.pdb

      - name: Get current Commit ID
        id: branch
        run: echo "::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)"

      - name: Release
      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          tag: ${{ steps.branch.outputs.branch }}
          name: ${{ steps.branch.outputs.branch }}
          allow_override: true
          draft: true
          body: >
            TODO New Release.
          gzip: folders
          files: >
            ${{ matrix.target.triple }}.zip:./target/${{matrix.target.triple}}/release/${{ matrix.target.triple }}.zip 

      - name: Clear the cargo caches
        run: |
          cargo install cargo-cache --version 0.8.2 --no-default-features --features ci-autoclean
          cargo-cache
